# Generic RAPP Platform Travis Continuous Integration Configuration File
# Author: Manos Tsardoulias 
# Contact: etsardou@gmail.com 
sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
notifications:
  email:
    recipients:
      - etsardou@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export ROS_DISTRO=indigo
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  # Perform system updates and install needed packages
  - echo "Installing needed libraries"
  - sudo apt-get update &> /dev/null
  - sudo apt-get install -qq -y git mercurial &> /dev/null
install: true # Use this to install any prerequisites or dependencies necessary to run your build
script: true# All commands must exit with code 0 on success. Anything else is considered failure.
after_success:

